### ISSUE TITLE
一个适配问题

### ISSUE THREAD

**Issue by zhuzhutai** [Jin-Yx/MQTT-Android#2]
`Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkPendingIntent(PendingIntent.java:430)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:733)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:720)
        at com.jinyx.mqtt.paho.AlarmPingSender.start(AlarmPingSender.java:75)
        at org.eclipse.paho.client.mqttv3.internal.ClientState.connected(ClientState.java:1209)
        at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:1045)
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:151)
        at java.lang.Thread.run(Thread.java:1012)`
催更适配啦~
现在的设备基本都是android13 14了，
demo跑起来连上会崩溃的...

**Comment by Jin-Yx** [comment]
implementation 'com.jinyx.mqtt:mqtt:0.0.2'

**Comment by Jin-Yx** [comment]
~~~
// 增加 jitpack 仓库依赖
maven { url "https://jitpack.io" }

dependencies {
    implementation 'com.github.Jin-Yx:MQTT-Android:0.0.2'
}
~~~
